---
title: "Welcome to My Website"
---

## Personl Interduction

My name is Yiyuan Li (Chris). Now I'm a student in Reed College studying mathematics and statistics as major and computer science as minor. 

I decided to change my academic interest to statistics and computer science on March 14, 2023, the day GPT-4 launched, after studying the humanities for three years in undergraduate. Prior to this shift, I worked at the intersection of political theory and the history of science, with a focus on Newtonian and Darwinian political metaphors in the nineteenth century and the rise of quantification in mid-twentieth-century social sciences.

The rise of large language models (LLMs) raises concerns for me about the potential loss of human self-respect. 
Many current applications of LLMs (e.g., tools like Cursor) emphasize replacing human labor, following what I call the "Replacement Paradigm," where technological advancements replace jobs that once gave people pride.

I aspire to work within a different paradigm—one focused on human empowerment.
My aim is to ensure that LLMs enhance human learning, fostering more profound reflection and discovery. 
LLMs should be tools that help us regain self-respect and boost our creative powers.
My work seeks to advance the empowerment paradigm to preserving human dignity.